name = "minecraft-infra-pack"
author = "ServerAdmin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f01ab44ae4db858012d6045625a72586b4de77bdd3f5ae431d0297603eadd68"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
