name = "minecraft-infra-pack"
author = "ServerAdmin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe5cd04bc892b169a435002c7b01683c6451fb09de802245c780205b2c7e974"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
